### PR TITLE
Add Swift Package Manager support

### PR DESCRIPTION
**Pull request by karimhm**

### CODE REVIEW

**Comment by devdev606** [comment]
karimhm:swift-pm

**Comment by petea** [comment]
@googlebot ping!

**Comment by tobihagemann** [comment]
@petea Just wanted to let you know that https://github.com/google/GTMAppAuth/commit/5a61635fa3c0458e3de72d126880ed035842cbe2 is problematic. Swift Package Manager doesn't work with iOS 7, at least on my Xcode 12. I cannot add GTMAppAuth as a dependency with that commit.

**Comment by petea** [comment]
@tobihagemann at what point do encounter a problem?

**Comment by phil1995** [comment]
If the Swift Package is added in Xcode via:
_File -> Swift Packages -> Add Package Dependency..._
the following error message appears:
GTMAppAuth_failed_to_parse_manifest_file

**Comment by petea** [comment]
@tobihagemann could you provide your full Xcode build version?  I'm not sure why I'm unable to reproduce.

**Comment by phil1995** [comment]
@petea I hope it's ok if I share my Xcode version since I get the bug as well. It is: Version 12.0.1 (12A7300)

**Comment by petea** [comment]
@tobihagemann @phil1995 try again with the updated Package.swift 319b2371c69138665d8cbd7c6700ceccbb49e04f

**Comment by phil1995** [comment]
@petea the import with [https://github.com/google/GTMAppAuth/commit/319b2371c69138665d8cbd7c6700ceccbb49e04f](https://github.com/google/GTMAppAuth/commit/319b2371c69138665d8cbd7c6700ceccbb49e04f ) works again without any problems.

**Pull request merged**
